[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:latest"

[target.x86_64-pc-windows-gnu]
image = "ghcr.io/cross-rs/x86_64-pc-windows-gnu:latest"
pre-build = [
    "dpkg --add-architecture i386",
    "apt-get update", 
    "apt-get install -y wine wine64"
]
runner = "wine64"
